### PR TITLE
Fixed bug #019388: eZComments proxy support for captcha

### PR DESCRIPTION
**Pull request by jjCavalleri**
While eZPublish allows proxy support for requests like URL check (see site.ini[ProxySettings]), eZComments doesn't take care of this configuration.

This results in the impossibility to use eZComments, protected with Captcha, on environments where proxy usage is mandatory.

### CODE REVIEW

**Comment by jjCavalleri** [comment]
Parameter $port is no longer being used. Should we remove it?

**Comment by xc** [comment]
There is one thing first: the code is not made by us, but by recaptcha(Google): http://code.google.com/p/recaptcha/downloads/list?q=label:phplib-Latest

Just wonder if it's ok to change here, or contribute it to Google...

**Comment by jjCavalleri** [comment]
That's a very good point.

According to the license included in that zip
"
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to 
deal in the Software without restriction, including without limitation the rights
to use, copy, _modify,_ merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
"

That was why I thought it to be cleaner to introduce a call to HTTPTool 
directly there...

**Comment by xc** [comment]
ok... thanks.Then I think you can add some copyright info to it(like modified by eZ Systems, etc)

I think the $port can be removed, yes.

**Pull request merged**
