### PR TITLE
Simple admin interface for eZ Comments

### PR DESCRIPTION
**Pull request by ghost**
A simple admin interface for comments, requested by one of our clients so sharing it upstream.

Admin interface lists all the available comments sorted by modified time, with pager at the bottom. Allows editing of comments and multiple delete.

Copy of previous pull request, now from separate branch.

See: https://github.com/ezsystems/ezcomments/pull/1

### CODE REVIEW

**Comment by netgen** [comment]
Corrected the issues you pointed out.

As for tab in admin interface, it's a request from client, so there it is. Also, look at eZ Find. Also has a tab and one item in left menu.

**Comment by xc** [comment]
I've retested the feature and it was good. 
(the tab might be an issue, but as we discussed in previous pull request, I think it's acceptable. And it's too late to put this request into current release, within next release we will add more features in the tab anyway).

NB: these is a enhancement http://issues.ez.no/IssueView.php?Id=18177 , otherwise it will only show admin-siteaccess language's comments.

**Comment by bdunogier** [comment]
Most customers I've seen managing comments did add a tab. So yes, in my opinion, it is a good idea.

Where are we with this now ?

**Comment by xc** [comment]
It's too late to put it into 4.5 release. I plan to merge them after release.

**Comment by bdunogier** [comment]
I was to review it before we pull it. I have pulled it locally, and I'm
giving it a try.

## 

Bertrand Dunogier

**Comment by xc** [comment]
merged to ezcomment 1.3.0 alpha, thanks you all ..  

https://github.com/ezsystems/ezcomments/commit/0d02b32a59484ec92d3f375d3192d3473293a481

**Pull request merged**
