### PR TITLE
Empty template causes PHP warning in eztemplate.php

### PR DESCRIPTION
**Pull request by jeromegamez**
With eZ Publish 4.5 this templates causes a PHP warning when completely empty:

Warning: array_merge() [function.array-merge]: Argument #2 is not an array in ezroot/lib/eztemplate/classes/eztemplate.php on line 1747

A simple HTML comment fixes that

### CODE REVIEW

**Comment by andrerom** [comment]
I think it should also work to have a line with:
{\* DO NOT EDIT THIS FILE! Use an override template instead. *}

**Comment by jeromegamez** [comment]
This looks more like ez, you're right, André.

I tried this first, too, but the error still remained. The "trick" was to include at least one whitespace or newline in addition to the comment itself.

**Comment by jeromegamez** [comment]
Don't mind the last to commits, bogus ones.

**Comment by andrerom** [comment]
Ok.

then I guess it does not help to use the following line in the top either:
{_?template charset=utf8?_}

(unsure if it should be "utf8" or "utf-8", only examples I found was with "latin1")

**Comment by jeromegamez** [comment]
Oh, I wasn't clear enough in my last comments: the change works as it is, I just had to include a newline after the comment - after that, the PHP warnings vanished.

**Comment by andrerom** [comment]
Also I thought this bug was fixed in eZ Publish in this commit\* btw so not sure this pull is needed.
- https://github.com/ezsystems/ezpublish/commit/a26164584337c69036aa9b4c3916aae74cdbe584

Correction, the commit for this warning would be:
https://github.com/ezsystems/ezpublish/commit/6fc1e092e675366b03f873de10423ffbece6af69

**Comment by jeromegamez** [comment]
What with those users who aren't on a current release/the master branch of eZ Publish, but still use the ezcomment extension (like us, we use the eZ Publish 4.5 Enterprise)

**Comment by andrerom** [comment]
So you say they would like to patch eZ Comments but not eZ Publish? :)

And if your using eZ Publish Enterprise, you could report the issue and point to that commit so it will become part of one of the next service packs.

**Comment by jeromegamez** [comment]
Exactly :).

In our current project, we can't patch a single file of the eZ Publish core, because we would turn our enterprise installation unsupported (if the change has not been approved by eZ Systems). Extensions are not validated by the ez_network.

**Comment by andrerom** [comment]
Ok, well you can do this locally if you want.
But I would say the proper fix for this is to fix it in eZ Publish, so closing.
But as mentioned if you report it, it will be in a service pack, hence be supported.

**Pull request closed without merging**
