### PR TITLE
Recaptcha error.

### PR DESCRIPTION
**Pull request by myxt**
When recaptcha is not configured globally, but on a siteaccess basis (every toplevel domain requires a unique recaptcha code) storing the content class will fail on a STATE_INVALID because the recaptcha is not configured for the admin siteaccess.
My suggestion is to just display the warning message, without sending the STATE_INVALID.

### CODE REVIEW

**Comment by xc** [comment]
@myxt, I think the way before this patch is logical. If the configuration is not global, then it should give an error because admin site access can not setup recaptcha correctly, right?(of course the admin account can use because it will bypass the recaptcha, but that's another mechanism)

I'm thinking If you just display warning message,  then it will not force user to setup the recaptcha key, which might cause usability problem..

**Comment by nfrp** [comment]
Hi, 

What is the final status on this ?

Cheers,

**Comment by xc** [comment]
Basically I think if the issue is as described, the solution should be looking for recaptcha key in front page site access(like 'ezflow' siteaccess) from admin siteaccess.

**Comment by nfrp** [comment]
> Basically I think if the issue is as described, the solution should be looking for recaptcha key in front page site access(like 
> 'ezflow' siteaccess) from admin siteaccess.

Which is usually quite difficult :)

**Comment by myxt** [comment]
Of course there is a simple workaround by adding a working or not-working key to the admin siteaccess ini, but since this is never really used I don't find it the most elegant solution.

Like I said, II would opt for a STATUS_WARNING and not STATUS_INVALID when storing the class and evaluating the datatype. Because the admin siteaccess doen not know the front-end siteaccess (afaik), the only real alternative is to display a message on the front-end when the user forgets to add the key there and views the comments.

Close or apply, do what you think is best ;-)

**Comment by xc** [comment]
I was/am in vacation. I will handle this after 10th. Sorry for the inconvenience.

**Pull request merged**
